In [2]:
import numpy as np

In [3]:
a2 = np.array([[1,2,3.5],
              [4,5,6.7]])
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6.7]])

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.7

In [6]:
a2.size

6

In [7]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
random_ar = np.random.rand(5,3)

In [9]:
random_ar

array([[0.42754077, 0.23652229, 0.81247393],
       [0.96231611, 0.91902341, 0.07352229],
       [0.91876506, 0.40671515, 0.06483176],
       [0.80808917, 0.86944342, 0.76500125],
       [0.1515149 , 0.14098571, 0.72683087]])

In [10]:
random_array = np.random.random((5,3))

In [11]:
random_array

array([[2.78046404e-01, 4.54191076e-01, 1.94319247e-01],
       [4.55159555e-01, 7.90486117e-01, 1.73539277e-01],
       [6.17065235e-01, 2.18295700e-01, 6.34485712e-05],
       [8.80288349e-01, 7.65173694e-01, 5.71839739e-01],
       [2.20321967e-02, 3.97569165e-01, 3.14922500e-01]])